# See https://wpvip.com/documentation/vip-go/syncing-data-on-vip-go/#domain-mapping-config
# TODO: Rename the site ID or slug (example) in the filename, too.
data_sync:
  domain_map:
    # Production > Staging
    example.com: develop.example.com
    www.example.com: develop.example.com
